[project]
name = "ml-ops"
version = "0.1.0"
description = "ML-OPS setup environment"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pre-commit>=4.2.0",
    "pydantic-settings>=2.8.1",
]
